import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

export default [
  {
    // Build output, caches and published data artifacts are never source.
    // data/ is generated by the ETL and is not hand-edited (see CLAUDE.md).
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/build/**",
      "**/coverage/**",
      "**/.vite/**",
      "data/**",
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    // The Academy API: Node, ESM JavaScript.
    files: ["apps/academy-api/**/*.js"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      globals: { ...globals.node },
    },
  },

  {
    // The Academy web client: browser React.
    files: ["apps/academy-web/**/*.{js,jsx}"],
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: "module",
      parserOptions: { ecmaFeatures: { jsx: true } },
      globals: { ...globals.browser },
    },
  },

  {
    // ETL packages and CLI: TypeScript on Node.
    files: ["packages/**/*.ts", "apps/etl-cli/**/*.ts", "tests/**/*.ts"],
    languageOptions: {
      globals: { ...globals.node },
    },
  },

  {
    // Tooling config files that are deliberately CommonJS.
    files: ["**/*.cjs"],
    languageOptions: {
      sourceType: "commonjs",
      globals: { ...globals.node },
    },
  },

  {
    // Console output is the ETL's and the API's logging surface.
    files: ["**/*.{ts,tsx,js,jsx}"],
    rules: {
      "no-console": "off",
      // Unused args are allowed when prefixed _, which this codebase already
      // does for Express's (_req, res) and similar signatures.
      "no-unused-vars": "off",
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
    },
  },
];
