# yaml-language-server: $schema=https://render.com/schema/render.yaml.json

services:
  - type: web
    name: efa-api
    plan: free
    runtime: node
    rootDir: .

    buildCommand: NODE_ENV=development pnpm i --frozen-lockfile=false && pnpm -C packages/shared build && pnpm -C packages/ui build && pnpm -C apps/api build
    startCommand: pnpm -C apps/api start

    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: "10000"
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: "7d"

staticSites:
  - name: efa-web
    plan: free
    rootDir: .
  
    buildCommand: NODE_ENV=development pnpm i --frozen-lockfile=false && pnpm -C packages/shared build && pnpm -C packages/ui build && pnpm -C apps/web build
    staticPublishPath: apps/web/dist
  
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
  
    envVars:
      - key: VITE_API_BASE_URL
        sync: false
